apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: -gold
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/version: small
    app.kubernetes.io/managed-by: operations
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-1
  databaseInitSQL:
    key: init.sql
    name: init-database
  postgresVersion: 13
  instances:
  - replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
