apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: -gold
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/version: medium
    app.kubernetes.io/managed-by: operations
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-14.0-3.1-0
  postgresVersion: 13
  databaseInitSQL:
    key: init.sql
    name: init-database
  instances:
    - name: 'pgc'
      replicas: 2
      resources:
        limits:
          cpu: 1.0
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
