apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: -gold
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/version: small
    app.kubernetes.io/managed-by: operations
spec:
  postgresVersion: 13
  instances:
    - name: 'pgc'
      replicas: 1
      resources:
        limits:
          cpu: 1.0
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi